# Generated by Django 3.1.2 on 2020-10-15 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('is_delivered', models.BooleanField(default=False)),
                ('inquiry_date', models.DateTimeField(default=datetime.datetime.now)),
                ('delivery_date', models.DateField(blank=True)),
            ],
        ),
    ]
