# Generated by Django 3.1.2 on 2020-10-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinquiry',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
