# Generated by Django 3.1.2 on 2020-10-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinquiry_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinquiry',
            name='delivery_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
