# Generated by Django 3.1.2 on 2020-10-09 10:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('fb_url', models.URLField(verbose_name='facebook URL')),
                ('insta_url', models.URLField(verbose_name='instagram URL')),
                ('twitter_url', models.URLField(verbose_name='twitter URL')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('web_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('isbn', models.IntegerField()),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('poetry', 'Poetry'), ('academics', 'Academics'), ('politics', 'Politics'), ('history', 'History'), ('comics', 'Comics')], max_length=100)),
                ('size', models.CharField(blank=True, help_text='Please use the following format: <em>l*b mm</em>.', max_length=20)),
                ('pages', models.IntegerField(blank=True)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('best_seller', models.BooleanField(default=False)),
                ('pick_of_the_week', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book_listings.author')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book_listings.publisher')),
            ],
        ),
    ]
