# Generated by Django 3.1.2 on 2020-10-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_listings', '0002_auto_20201009_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
