# Generated by Django 3.1.2 on 2020-10-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_listings', '0003_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='fb_url',
            field=models.URLField(blank=True, verbose_name='facebook URL'),
        ),
        migrations.AlterField(
            model_name='author',
            name='insta_url',
            field=models.URLField(blank=True, verbose_name='instagram URL'),
        ),
        migrations.AlterField(
            model_name='author',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='twitter URL'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('poetry', 'Poetry'), ('academics', 'Academics'), ('politics', 'Politics'), ('history', 'History'), ('comics', 'Comics'), ('non-fiction', 'Non-fiction')], max_length=100),
        ),
    ]
